Add Mojo execution tests and 'sourceGenerationFormat' property
makubi/avrohugger-maven-plugin pull request #12
Opened 2017-07-01 20:34 UTC by makubi

* sourceGenerationFormat maps to SourceFormat of avrohugger
* Tests for Mojo executions

2017-07-03 11:06 UTC, mariussoutier requested changes

2017-07-03 11:06 UTC, mariussoutier commented on src/main/java/at/makubi/maven/plugin/avrohugger/Defaults.java
> +    String sourceGenerationFormat = "SPECIFIC_RECORD";
Can you use the `SourceGenerationFormat` enum here?

2017-07-03 11:06 UTC, mariussoutier commented on src/main/java/at/makubi/maven/plugin/avrohugger/Defaults.java
> +    String sourceGenerationFormat = "SPECIFIC_RECORD";
I'd also use a boolean or enum for the two boolean fields, better documentation, less stringly typing.

2017-07-03 15:29 UTC, makubi commented on src/main/java/at/makubi/maven/plugin/avrohugger/Defaults.java
> +    String sourceGenerationFormat = "SPECIFIC_RECORD";
I would like to, but the defaults have to be constant String values.

2017-07-04 07:12 UTC, mariussoutier approved these changes

2017-07-04 07:12 UTC, mariussoutier commented on src/main/java/at/makubi/maven/plugin/avrohugger/Defaults.java
> +    String sourceGenerationFormat = "SPECIFIC_RECORD";
Too bad, but ok for the time being.

2017-07-04 07:43 UTC, merged