Add support for date and timestamp typeOverrides
makubi/avrohugger-maven-plugin pull request #26
Opened 2020-06-18 06:25 UTC by algorri94

2020-06-23 08:34 UTC, algorri94 commented
@makubi can you take a look at this PR please?

2020-07-09 09:08 UTC, makubi commented
Hi @algorri94 and thanks for the PR! Could you move the `AvroScalaTimestampMillisType` and `AvroScalaDateType` files to the `complex` package and add an entry in the typeOverrides at https://github.com/makubi/avrohugger-maven-plugin/blob/master/src/test/resources/unit/avrohugger-maven-plugin/mojo/overwrite/pom-overwrite.xml?

2020-07-10 07:34 UTC, algorri94 commented
Done! Thanks for reviewing!

2020-07-17 08:33 UTC, makubi requested changes
Thanks. I've made some suggestions. What do you think? Could you squash the two commits into one and change the source branch to something else than master?

2020-07-17 08:33 UTC, makubi commented on src/main/java/at/makubi/maven/plugin/avrohugger/typeoverride/complex/AvroScalaDateType.java
> +    TIME_LOCALDATE(avrohugger.types.JavaTimeLocalDate$.MODULE$);
```suggestion
    JAVA_TIME_LOCAL_DATE(avrohugger.types.JavaTimeLocalDate$.MODULE$);
```

2020-07-17 08:33 UTC, makubi commented on src/main/java/at/makubi/maven/plugin/avrohugger/typeoverride/complex/AvroScalaDateType.java
> +    SQL_DATE(avrohugger.types.JavaSqlDate$.MODULE$),
```suggestion
    JAVA_SQL_DATE(avrohugger.types.JavaSqlDate$.MODULE$),
```

2020-07-17 08:33 UTC, makubi commented on src/main/java/at/makubi/maven/plugin/avrohugger/typeoverride/complex/AvroScalaTimestampMillisType.java
> +    INSTANT(avrohugger.types.JavaTimeInstant$.MODULE$),
```suggestion
    JAVA_TIME_INSTANT(avrohugger.types.JavaTimeInstant$.MODULE$),
```

2020-07-17 08:33 UTC, makubi commented on src/main/java/at/makubi/maven/plugin/avrohugger/typeoverride/complex/AvroScalaTimestampMillisType.java
> +    TIMESTAMP(avrohugger.types.JavaSqlTimestamp$.MODULE$);
```suggestion
    JAVA_SQL_TIMESTAMP(avrohugger.types.JavaSqlTimestamp$.MODULE$);
```

2020-07-17 08:33 UTC, makubi commented on src/main/scala/at/makubi/maven/plugin/avrohugger/Implicits.scala
> +      nonNullOrDefault(optionalTimestampMillis)(timestamp => avroScalaTypes.copy(timestampMillis = timestamp))
```suggestion
      nonNullOrDefault(optionalTimestampMillis)(timestampMillis => avroScalaTypes.copy(timestampMillis = timestampMillis))
```

2020-07-17 08:33 UTC, makubi commented on src/main/scala/at/makubi/maven/plugin/avrohugger/Implicits.scala
> +      nonNullOrDefault(optionalDate)(timestamp => avroScalaTypes.copy(date = timestamp))
```suggestion
      nonNullOrDefault(optionalDate)(date => avroScalaTypes.copy(date = date))
```

2020-07-17 08:33 UTC, makubi commented on src/test/resources/unit/avrohugger-maven-plugin/mojo/overwrite/pom-overwrite.xml
> +                        <dateType>TIME_LOCALDATE</dateType>
Could you change this two overrides to non-defaults and update the https://github.com/makubi/avrohugger-maven-plugin/blob/master/src/test/resources/unit/avrohugger-maven-plugin/mojo/TypeOverrides.avdl and https://github.com/makubi/avrohugger-maven-plugin/blob/master/src/test/resources/unit/avrohugger-maven-plugin/mojo/overwrite/TypeOverridesRecord.scala to include one field for each?

2026-02-04 21:56 UTC, closed without merging