Add support for restricted fields in class generation for compatibility with Scala 2.10
makubi/avrohugger-maven-plugin pull request #9
Opened 2017-05-05 20:54 UTC by sini

Scala 2.10 case classes are limited to 22 fields. AVRO schema definitions exceeding this number of fields fail to generate compatible case classes. Exposing this flag allows users to optionally generate classes instead of case classes for records that exceed 22 fields.

2017-05-10 10:36 UTC, mariussoutier reviewed
Looks good in general, not sure if there should be a test case that covers this flag though.

2017-05-10 14:53 UTC, mariussoutier requested changes

2017-05-10 14:53 UTC, mariussoutier commented on README.md
> +            <restrictedFields>true</restrictedFields>>
`restrictedFields` sounds a bit vague to me. Could you make it more explicit by renaming to `limitedNumberOfFieldsInCaseClasses`?

2017-05-10 17:47 UTC, mariussoutier approved these changes

2017-05-12 08:45 UTC, makubi commented
Thank you for updating the PR @sini. Could you squash the commits to one? Thanks!

2017-05-16 18:42 UTC, sini commented
Done. Sorry for the delay. :)

2017-05-17 09:16 UTC, merged

2017-05-18 00:01 UTC, sini commented
Would it be possible to get a release pushed with this change? I've got a project thats dependent on it and it would be great if others could build it.

2017-05-18 15:06 UTC, mariussoutier commented
Sorry I don't have sufficient privileges for a release. @makubi isn't available right now, but he will do a release at the end of the month.

2017-05-31 08:21 UTC, makubi commented
@sini Sorry for the delay. 1.3 should be synced to central soon.